defmodule FrontendExWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :frontend_ex

  # Parity routes intentionally avoid sessions/CSRF. Keep the endpoint lean to
  # reduce overhead and avoid cookie parsing/signing on every request.

  @session_options [
    store: :cookie,
    key: "_frontend_ex_key",
    signing_salt: "EF6QTIu+",
    same_site: "Lax"
  ]

  # Needed for LiveDashboard (and any future LiveView-based pages).
  socket "/live", Phoenix.LiveView.Socket, websocket: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :frontend_ex,
    gzip: not code_reloading?,
    only: FrontendExWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug FrontendExWeb.Router
end
